name: pawfect_care
description: "A cross-platform app for pet care management, veterinary services, and pet adoption."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.1
  go_router: ^13.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.2
  image_picker: ^1.0.7
  http: ^1.2.0
  dio: ^5.4.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.5
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.1.1
  firebase_performance: ^0.9.2+1
  google_sign_in: ^6.1.6
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # UI
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  device_preview: ^1.1.0
  
  # Utils
  intl_phone_field: ^3.1.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  timezone: ^0.9.2
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

  # Code generation
  json_serializable: ^6.7.2
  freezed: ^2.4.7
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.4.0

  # Payments
  stripe_payment: ^1.1.4

  # Video Player
  video_player: ^2.8.2

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/images/dog1.jpg
    - assets/images/dog2.jpg
    - assets/images/dog3.jpg
    - assets/images/pet1.jpg
    - assets/images/pet2.jpg
    - assets/images/pet3.jpg
    - assets/images/pet4.jpg
    - assets/images/pet5.jpg
    - assets/images/pet6.jpg
    - assets/images/pet7.jpg
    - assets/images/pet8.jpg
    - assets/images/pet9.jpg
    - assets/images/pet10.jpg
    - assets/images/pet11.jpg
    - assets/images/pet12.jpg
    - assets/images/pet13.jpg
    - assets/images/pet14.jpg
    - assets/images/pet15.jpg
    - assets/images/pet16.avif
    - assets/images/pet17.jpg
    - assets/images/pet18.jpg
    - assets/images/pet19.jpg
    - assets/images/pet20.jpg
    - assets/images/pet21.jpeg
    - assets/images/shirt1-removebg-preview.png
    - assets/images/shirt2-removebg-preview.png
    - assets/images/shirt3-removebg-preview.png
    - assets/images/shirt4-removebg-preview.png
    - assets/images/shirt5-removebg-preview.png
    - assets/images/shirt6-removebg-preview.png
    - assets/images/shirt7-removebg-preview.png
    - assets/images/shirt8-removebg-preview.png
    - assets/images/shirt9-removebg-preview.png
    - assets/images/shirt10-removebg-preview.png
    - assets/images/shirt11-removebg-preview.png
    - assets/images/shirt12-removebg-preview.png
    - assets/images/shirt13-removebg-preview.png
    - assets/images/pfood1-removebg-preview.png
    - assets/images/pfood2-removebg-preview.png
    - assets/images/pfood3-removebg-preview.png
    - assets/images/pfood4-removebg-preview.png
    - assets/images/pfood5-removebg-preview.png
    - assets/images/pfood6-removebg-preview.png
    - assets/images/pfood7-removebg-preview.png
    - assets/images/pfood8-removebg-preview.png
    - assets/images/pfood9-removebg-preview.png
    - assets/images/pfood10-removebg-preview.png
    - assets/images/pfood11-removebg-preview.png
    - assets/images/pfood12-removebg-preview.png
    - assets/images/pfood13-removebg-preview.png
    - assets/images/pfood14-removebg-preview.png
    - assets/images/pfood15-removebg-preview.png
    - assets/images/pfood16-removebg-preview.png
    - assets/images/pfood17-removebg-preview.png
    - assets/images/pfood18-removebg-preview.png
    - assets/images/pfood19-removebg-preview.png
    - assets/images/pfood20-removebg-preview.png
    - assets/images/pfood21-removebg-preview.png
    - assets/images/pfood22-removebg-preview.png
    - assets/images/pfood23-removebg-preview.png
    - assets/images/pfood24-removebg-preview.png
    - assets/images/pfood25-removebg-preview.png
    - assets/images/pfood26-removebg-preview.png
    - assets/images/sale1-removebg-preview.png
    - assets/images/sale2-removebg-preview.png
    - assets/images/sale3-removebg-preview.png
    - assets/images/sale4-removebg-preview.png
    - assets/images/sale6-removebg-preview.png
    - assets/images/sale7-removebg-preview.png
    - assets/images/sale8-removebg-preview.png
    - assets/images/sale9-removebg-preview.png
    - assets/images/sale11-removebg-preview.png
    - assets/images/sale12-removebg-preview.png
    - assets/images/sale13-removebg-preview.png
    - assets/images/sale14-removebg-preview.png
    - assets/images/sale15-removebg-preview.png
    - assets/images/sale16-removebg-preview.png
    - assets/images/sale17-removebg-preview.png
    - assets/images/sale18-removebg-preview.png
    - assets/images/sale19-removebg-preview.png
    - assets/images/sale20-removebg-preview.png
    - assets/images/sale21-removebg-preview.png
    - assets/images/sale22-removebg-preview.png
    - assets/images/sale23-removebg-preview.png
    - assets/images/sale24-removebg-preview.png
    - assets/images/sale25-removebg-preview.png
    - assets/images/sale26-removebg-preview.png
    - assets/images/sale27-removebg-preview.png
    - assets/images/sale29-removebg-preview.png
    - assets/images/sale30-removebg-preview.png
    - assets/images/sale31-removebg-preview.png
    - assets/images/sale32-removebg-preview.png
    - assets/images/sale33-removebg-preview.png
    - assets/images/sale34-removebg-preview.png
    - assets/images/sale35-removebg-preview.png
    - assets/images/sale_28-removebg-preview.png
    - assets/images/sales5-removebg-preview.png
    - assets/images/stuff5-removebg-preview.png
    - assets/images/stuff6-removebg-preview.png
    - assets/images/stuff7-removebg-preview.png
    - assets/images/stuff17-removebg-preview.png
    - assets/images/stuff18-removebg-preview.png
    - assets/images/stuff19-removebg-preview.png
    - assets/images/stuff20-removebg-preview.png
    - assets/images/stuff22-removebg-preview.png
    - assets/images/stuff23-removebg-preview.png
    - assets/images/stuff24-removebg-preview.png
    - assets/images/stuff25-removebg-preview.png
    - assets/images/stuff26-removebg-preview.png
    - assets/images/stuff27-removebg-preview.png
    - assets/images/stuff28-removebg-preview.png
    - assets/images/stuff29-removebg-preview.png
    - assets/images/stuff30-removebg-preview.png
    - assets/images/stuff31-removebg-preview.png
    - assets/images/stuff39-removebg-preview.png
    - assets/images/stuff40-removebg-preview.png
    - assets/images/stuffs32-removebg-preview.png
    - assets/images/stuffs33-removebg-preview.png
    - assets/images/stuffs34-removebg-preview.png
    - assets/images/stuffs35-removebg-preview.png
    - assets/images/stuffs36-removebg-preview.png
    - assets/images/stuffs38-removebg-preview.png
    - assets/images/suff21-removebg-preview.png
    - assets/images/mixkit-dog-catches-a-ball-in-a-river-1494-4k.mp4
    - assets/images/mixkit-dog-sitting-on-log-1550-4k.mp4
    - assets/images/mixkit-lizard-over-a-trunk-at-nature-closeup-1473-4k.mp4
    - assets/images/mixkit-macaw-parrot-feeding-on-a-branch-4669-4k.mp4
    - assets/images/mixkit-pet-owner-playing-with-a-cute-cat-1779-full-hd.mp4
